services:
  - type: web
    name: quiz-system
    env: node
    plan: free
    autoDeploy: true
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    disk:
      name: quiz-data
      mountPath: /data
      sizeGB: 1
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATA_PATH
        value: /data/db.json
      - key: NPM_CONFIG_PRODUCTION
        value: false
    routes:
      - type: rewrite
        source: /*
        destination: /

