services:
  - type: web
    name: quiz-system
    env: node
    plan: free
    autoDeploy: true
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm start
    healthCheckPath: /
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
    envVars:
      - key: CI
        value: true
      - key: NPM_CONFIG_PRODUCTION
        value: false
      - key: DATA_PATH
        value: /data/db.json

